flags: {}
packages:
- '.'
- location:
    git: git@github.com:Twinside/HPDF
    commit: 090c08ab61a237c721a307f5cf9fd33f3988b82e
  extra-dep: true
extra-deps:
- OpenAL-1.7.0.0
- hsndfile-0.7.1
- hsndfile-vector-0.5.2
- rubberband-0.1.0.2
- sdl2-image-0.1.3.2
- jammittools-0.5.0.1
- HPDF-1.4.6
- boxes-0.1.4
- conduit-audio-0.1
- FindBin-0.0.5
resolver: nightly-2015-06-28
